# Server configuration
server.port=8082

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pretty
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger UI configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/api-docs
springdoc.swagger-ui.config-url=/api-docs/swagger-config
springdoc.swagger-ui.version=5.2.0

# Logging configuration
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=INFO
