# Server configuration
server.port=8082

# Swagger UI configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.title=Pretty Platform API
springdoc.swagger-ui.description=API documentation for Pretty company platform
springdoc.swagger-ui.version=1.0.0

# Logging configuration
logging.level.org.springdoc=INFO
logging.level.org.springframework.web=INFO