basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is a sample server.
  title: Hello World API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: get hello world
      produces:
      - application/json
      responses:
        "200":
          description: hello world
          schema:
            type: string
      summary: Get hello world
      tags:
      - hello
swagger: "2.0"
